builds:
  -
    main: ./.goreleaser/main.go
    binary: dirty-hack
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: 386
archive:
  name_template: "dirty-hack-for-goreleaser"
  files:
    - README.md
release:
  name_template: "{{.Tag}}"
